services:
   pgadmin:
      container_name: ms-pgadmin
      image: dpage/pgadmin4
      environment: 
         PGADMIN_DEFAULT_EMAIL: anurapkasthoori@gmail.com
         PGADMIN_DEFAULT_PASSWORD: password
      volumes:
         - pgadmin:/var/lib/pgadmin
      ports:
         - "5050:80"
      networks:
         - microservices-net
 
         
   postgres:
      container_name: ms-postgres-db
      image: postgres
      environment:
         POSTGRES_USER: admin
         POSTGRES_PASSWORD: password
         POSTGRES_DB: productdb
      volumes:
         - postgres_data:/var/lib/postgresql/data
      networks:
         - microservices-net
      ports:
         - "5432:5432"
         
networks:
   microservices-net:
      driver: bridge
      name: microservices-net
         
volumes:
   postgres_data:
   pgadmin:
 
         
   
         